// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ProjetoAbais.API.Models;

public partial class abaisdbContext : DbContext
{
    public abaisdbContext(DbContextOptions<abaisdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Administrador> Administradors { get; set; }

    public virtual DbSet<Aluguel> Aluguels { get; set; }

    public virtual DbSet<Imovel> Imovels { get; set; }

    public virtual DbSet<Inquilino> Inquilinos { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Administrador>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__administ__3213E83FCA893D9D");
        });

        modelBuilder.Entity<Aluguel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__aluguel__3213E83F375D4E7F");

            entity.HasOne(d => d.Administrador).WithMany(p => p.Aluguels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__aluguel__adminis__45F365D3");

            entity.HasOne(d => d.Imovel).WithMany(p => p.Aluguels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__aluguel__imovel___46E78A0C");

            entity.HasOne(d => d.Inquilino).WithMany(p => p.Aluguels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__aluguel__inquili__44FF419A");
        });

        modelBuilder.Entity<Imovel>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__imovel__3213E83FCDE51795");
        });

        modelBuilder.Entity<Inquilino>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__inquilin__3213E83F88FA696C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}