// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetoAbais.API.Models;

[Table("administrador")]
public partial class Administrador
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("telefone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Required]
    [Column("senha")]
    [StringLength(255)]
    [Unicode(false)]
    public string Senha { get; set; }

    [InverseProperty("Administrador")]
    public virtual ICollection<Aluguel> Aluguels { get; set; } = new List<Aluguel>();
}