// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetoAbais.API.Models;

[Table("aluguel")]
public partial class Aluguel
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("dataInicio", TypeName = "date")]
    public DateTime DataInicio { get; set; }

    [Column("dataFim", TypeName = "date")]
    public DateTime? DataFim { get; set; }

    [Column("valor")]
    public int Valor { get; set; }

    [Column("pagamento")]
    [StringLength(20)]
    [Unicode(false)]
    public string Pagamento { get; set; }

    [Column("inquilino_id")]
    public int InquilinoId { get; set; }

    [Column("administrador_id")]
    public int AdministradorId { get; set; }

    [Column("imovel_id")]
    public int ImovelId { get; set; }

    [ForeignKey("AdministradorId")]
    [InverseProperty("Aluguels")]
    public virtual Administrador Administrador { get; set; }

    [ForeignKey("ImovelId")]
    [InverseProperty("Aluguels")]
    public virtual Imovel Imovel { get; set; }

    [ForeignKey("InquilinoId")]
    [InverseProperty("Aluguels")]
    public virtual Inquilino Inquilino { get; set; }
}