// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetoAbais.API.Models;

[Table("imovel")]
public partial class Imovel
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(20)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("descricao")]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(50)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [InverseProperty("Imovel")]
    public virtual ICollection<Aluguel> Aluguels { get; set; } = new List<Aluguel>();
}