// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ProjetoAbais.API.Models;

[Table("inquilino")]
[Index("Email", Name = "UQ__inquilin__AB6E616441B0D2D5", IsUnique = true)]
[Index("Cpf", Name = "UQ__inquilin__D836E71FE6DCA551", IsUnique = true)]
public partial class Inquilino
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("telefone")]
    [StringLength(20)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Required]
    [Column("cpf")]
    [StringLength(20)]
    [Unicode(false)]
    public string Cpf { get; set; }

    [Column("email")]
    [StringLength(255)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [Column("endereco")]
    [StringLength(255)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [InverseProperty("Inquilino")]
    public virtual ICollection<Aluguel> Aluguels { get; set; } = new List<Aluguel>();
}